
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python deps
        run: |
          pip install -r requirements.txt || true
          pip install pytest dbt-core dbt-bigquery dbt-snowflake
      - name: Lint
        run: |
          python -m py_compile $(git ls-files '*.py') || true
      - name: Pytests
        run: pytest -q
      - name: dbt compile
        run: |
          cd dbt
          dbt deps
          dbt compile
