
name: Terraform

on:
  workflow_dispatch:
  pull_request:
    paths: ["terraform/**"]

jobs:
  tf-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
      - name: Validate GCP
        working-directory: terraform/gcp
        run: |
          terraform init -backend=false
          terraform validate
      - name: Validate Snowflake
        working-directory: terraform/snowflake
        run: |
          terraform init -backend=false
          terraform validate
